name: Infinite Loving Empire
favicon: null
layout_spectrum: 0.04969764547422528
typography_spectrum: 0.06541171087883413
title: Infinite Loving Empire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1d1a'
    - '#86b4d8'
    - '#425772'
    - '#80828f'
  brandStrength: 1
  lightness: 0.42171587445773184
  saturation: 0.8695529364049435
  rhythmicContrast: 0.45246204594150186
purpose: []
