name: Infinite Loving Empire
favicon: null
layout_spectrum: 0.04969764547422528
typography_spectrum: 0.06541171087883413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05289903120137751
  lightness: 0.42171587445773184
  saturation: 0.8695529364049435
  rhythmicContrast: 0.45246204594150186
purpose: []
